# Generated by Django 5.2.7 on 2025-10-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('aqi_us', models.IntegerField()),
                ('pm10', models.FloatField(null=True)),
                ('pm2_5', models.FloatField(null=True)),
                ('o3', models.FloatField(null=True)),
                ('no2', models.FloatField(null=True)),
                ('so2', models.FloatField(null=True)),
                ('co', models.FloatField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='aqi.location')),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'ts'], name='aqi_measure_locatio_6da46a_idx')],
                'unique_together': {('location', 'ts')},
            },
        ),
    ]
