# Generated by Django 5.2.7 on 2025-11-04 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_app_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_pm2_5', models.BooleanField(default=True)),
                ('can_pm10', models.BooleanField(default=True)),
                ('can_o3', models.BooleanField(default=True)),
                ('can_co', models.BooleanField(default=True)),
                ('can_no2', models.BooleanField(default=True)),
                ('can_so2', models.BooleanField(default=True)),
                ('can_aqi', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
